version: "3.8"

services:

  web-server:
    build:
      dockerfile: .dockerfile
      context: .
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "app:/var/www"
    networks:
      - app-network

  mysql-server:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./app/database:/docker-entrypoint-initdb.d"
      - "db:/var/lib/mysql"
    ports:
      - "3306:3306"

networks:
  app-network:

volumes:
  db:
  app:
