version: "3.8"

services:

  web-server:
    build:
      dockerfile: .dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    ports:
      - "80:80"
    networks:
      - app-network

  mysql-server:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"

networks:
  app-network:

volumes:
  db:
